### 添加文档（分配随机ID）
POST http://localhost:9200/index_curd/_doc
Content-Type: application/json

{
  "username": "zhangsan",
  "password": "123456",
  "enable": 0
}

### 添加文档（自定义ID值）
PUT http://localhost:9200/index_curd/_doc/9527
Content-Type: application/json

{
  "username": "lisi",
  "password": "123456",
  "enable": 0
}

### 查看索引中的所有文档
GET http://localhost:9200/index_curd/_search

### 根据ID查看文档
GET http://localhost:9200/index_curd/_doc/9527

### 根据ID修改文档
PUT http://localhost:9200/index_curd/_doc/9527
Content-Type: application/json

{
  "password": "888888"
}

### 修改文档中的部分字段的值
POST http://localhost:9200/index_curd/_doc/9527/_update
Content-Type: application/json

{
  "doc": {
    "password": "lisi888",
    "nickname": "小李同学"
  }
}

### 根据ID删除文档
DELETE http://localhost:9200/index_curd/_doc/68Dum4oBJqkR4YpX38WB

### 删除索引
DELETE http://localhost:9200/index_curd