### 查看索引的基本状态
GET http://localhost:9200/mall_goods

### 删除索引
DELETE http://localhost:9200/mall_goods

### 查看索引中的所有文档
GET http://localhost:9200/mall_goods/_search

### 查看数据
GET http://localhost:9200/mall_goods/_doc/999

### 指定条件的搜索：复合条件，其中，must >>> AND / should >>> OR / must_not >>> !=
GET http://localhost:9200/mall_goods/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "categoryName": "绿茶"
          }
        },
        {
          "match": {
            "barCode": "绿茶"
          }
        },
        {
          "match": {
            "title": "绿茶"
          }
        },
        {
          "match": {
            "brief": "绿茶"
          }
        },
        {
          "match": {
            "keyword": "绿茶"
          }
        }
      ]
    }
  }
}