spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_tea_mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

server:
  port: 19081

logging:
  level:
    cn.tedu.tmall: trace

tmall:
  jwt:
    secret-key: 8KS7u4F9ufaJa7sPD3fDa
    duration-in-minute: 43200